### ISSUE TITLE
Event handler not triggered 

### ISSUE THREAD

**Issue by Bretto** [elix/elix#100]
Awesome work, I am doing some test in the devtools console on the site components. 
How come if I ```monitorEvents(elix-expandable-panel)``` I don't get the __opened-changed__ event.
But I do get the __selected-index-changed__  when ```monitorEvents(elix-list-box)```

**Comment by JanMiksovsky** [comment]
Thanks for the report! I'll investigate later this week when I'm back at work.

**Comment by JanMiksovsky** [comment]
I believe the discrepancy you're seeing is the difference between a property indirectly changed by a user interaction with a component versus a property directly changed by code outside the component.

As laid out in [Property Change Events](https://github.com/webcomponents/gold-standard/wiki/Property-Change-Events), web components are supposed to only raise events for properties that change in response to internal user interaction of which the outer page has no knowledge. If the outer page is directly modifying a component property, the component is expected to *not* raise a change event. The page already knows the property is changing — since it's the page that's initiating the change — so the thinking is that the page doesn't need to get an event as well.

In the case of ExpandablePanel, that component exposes no UI of its own for modifying the `opened` property; it can only be modified from the outside. In the demo at http://localhost:5000/demos/expandablePanel.html, the Expand/Collapse button is provided by the page, and clicks on that button have the page tell the ExpandablePanel to open or close. Per the above Property Change Events guideline, the component does *not* raise opened-changed.

A component could extend ExpandablePanel, or compose an instance of an ExpandablePanel internally, and provide its own UI for expanding and collapsing. This is the case with, for example, ExpandableSection, which composes an instance of ExpandablePanel, but provides a section header that can be clicked to toggle the `opened` property. In the demo at http://localhost:5000/demos/expandableSection.html, when the user clicks on a section header, the outer page has no way of knowing about the change in the value of the `opened` property, so in that case ExpandableSection *does* raise an opened-changed event.

(For the same reason, ListBox raises a selected-index-changed event when you click on an item, because the outer page has no other way of knowing about a change in selection. If you programmatically change the selection, by setting `selectedIndex`, say, then the ListBox does not raise the event.)

I agree that this is rather confusing. In fact, reflecting on this, I'm not quite sure how we can easily document events like opened-changed in a clear way to indicate when the event is going to be raised. I'll give that some thought.

If you think something else is going on here, please let me know. Otherwise, I think this behavior is by design.

**Comment by Bretto** [comment]
Thank you very much for this expert explanation, this makes perfect sense now.
