### ISSUE TITLE
Serene tabs don't fire selected-index-changed consistently if selected-index set programmatically

### ISSUE THREAD

**Issue by bahrus** [elix/elix#104]
See demo [here](https://bahrus.github.io/elix/tabTest.html)  

If I click directly on the tabs, the selected-index-changed event fires consistently.

However, the buttons, which set selected-index programmatically, the event only fires the first time.

**Comment by JanMiksovsky** [comment]
Thanks for reporting this — although I can't run the demo to see the problem. Instead, I see various console errors.

From your description, I'm guessing that the behavior here is primarily by design. Generally speaking, programmatically setting an element's properties from the outside do _not_ raise change events. See this [issue](https://github.com/elix/elix/issues/100) for a longer discussion.

I'm not quite sure why you see the event fire at all when you click the buttons, though. If I could get the demo to run, I could take a closer look.

I did notice that the provided repro case loads a large number of files outside of Elix, which will make it hard to isolate Elix behavior from the behavior of those other files. It would be easier to diagnose the problem if the repro case only used the Elix source plus the smallest amount of JS required to trigger the problem.

**Comment by bahrus** [comment]
Apologies for the buggy/confusing demo.  I'm surprised you are getting console errors (I'm getting one for a broken image, but that shouldn't affect anything).  I've tested on Chrome, Firefox and Safari (iPad).  Do you mind giving me more details as to your browser (version, os?) and provide the error(s)?  

At any rate, I've created a second test page [here](https://bahrus.github.io/elix/tabTest2.html), but I think you have captured the essence of the issue despite my confusing demo.

I would suggest not following the precedent set by ancient elements like the listbox, but look instead to newer elements, like details / summary.  I find that if I set the"open" property of a details element programmatically, it still fires the "toggle" event.  I can create a demo of that as well, if you'd like.

Being able to subscribe to the event, and not care *how* the tab (or details panel) was opened, whether by a user click, or by another loosely coupled component, makes reasoning and development quite a bit easier in my opinion.  It might be nice to indicate whether the event was fired, adding a flag in the detail of the event.

Without that capability, the thing that causes the tabs to change has to be tightly coupled to the thing that responds to the tab changing.  This might be a nicer design in some circumstances, but I would argue not always (maybe 50/50?)  I think it would be great if the developer could decide what makes sense.

Thanks for considering this issue, feel free to close if you disagree.

**Comment by JanMiksovsky** [comment]
Thanks for creating a simpler demo.

I myself would much prefer for components to always raise property changes events, and Elix components originally did that. But the clear recommendation from browser vendors has been to follow the precedent of the native HTML elements, which — with few exceptions — do not raise property changes events in response to having properties programmatically set from the outside.

My understanding is that this is fundamentally for better performance. (Moreover, some data binding systems have now come to depend upon that behavior, and can enter infinite loops if they encounter elements that raise property change events unexpectedly.) Google indicates as much in the [Events](https://developers.google.com/web/fundamentals/web-components/best-practices#events) section of their Best Practices document for web components.

We likewise followed the browser vendors' recommendation and the HTML precedent in putting together the Gold Standard Checklist for Web Components. We want to provide components that mirror native HTML element behavior (even if that behavior is not 100% uniform). We also want to provide components whose behavior is as predictable as possible, even if that means reproducing behavior we personally think is confusing. If all component authors generally try to follow the browser vendors' recommendations, then all component users have an easier time predicting how components will behave — _even if that behavior is annoying!_

So we're going to leave the current behavior in place.

Aside: the fact that the tabs component does raise the first selected-index-changed event is a side effect of how Elix components handle slotted content. The light DOM contents placed inside a component can have broad effects on multiple properties. Among other things, if the outside page _removes_ an item from an `<elix-tabs>` component, it's possible the component may need to updated its `selected-index` property in response. The page has no way of knowing whether or not manipulating the DOM inside the tabs component is going to updated `selected-index`, so to be on the safe side, Elix components _do_ raise property change events in response to changes in slotted content. That includes the "change" that happens when a component is first placed into the DOM or, in this case, when the page is loaded.

FWIW, in cases where page does have A) tabs tightly coupled to B) something that responds to the selected tab, one strategy is to reflect that coupling in a wrapping component holding both A and B. That wrapper can handle the coupling, and the outer page won't need to worry about it. Obviously, that strategy only works if A and B are adjacent in the layout.

**Comment by bahrus** [comment]
Thanks for pointing me to the best practices link, and your explanation for the unexpected inconsistency between the first selection and subsequent selections.  I had not yet absorbed that advice on best practices related events.  I can see how some binding frameworks could end up in an infinite loop if not careful (especially when the event is tightly coupled to a passed in property).  

I will adjust my way of thinking in accordance with this.

**Comment by bahrus** [comment]
You might be interested to know that the [material tab component](https://material-components.github.io/material-components-web-components/demos/tabs.html) currently emits event: MDCTabBar:activated as one sets $0.activeIndex (where $0 = mwc-tab-bar ), just like when you click. Just saying :-)

Also, the reason I came across this issue is kind of interesting -- we have two expandable grids, which we are placing inside your tabs.  We like the animation effect you have, it's quite nice.  But we found that since neither grid ever get set to "display:none" (in order to achieve the animation effect, I'm sure), we had to set z-index of the "hidden" grid to -1 in order to add clarity about which grid was currently active (click events were somewhat unpredictable which grid we were clicking on).  Eventually we also put a delayed display:none to avoid other issues.

I guess it would be helpful if you could fire an event after the animation has run its course, if possible.   
 And/or actually set display:none after it has finished.  I recognize this isn't part of your main component offering, but just wanted to let you know what our experience was.  

And of course, thanks for providing this cool library of components.

**Comment by JanMiksovsky** [comment]
> You might be interested to know that the material tab component currently emits event: MDCTabBar:activated as one sets $0.activeIndex (where $0 = mwc-tab-bar ), just like when you click. Just saying :-)

Heh, touché. I still think we're better off listening to what the people who make the actual platform recommend. Those recommendations may still be correct, even if some people who work for a browser vendor don't follow them.

> Also, the reason I came across this issue is kind of interesting -- we have two expandable grids, which we are placing inside your tabs. We like the animation effect you have, it's quite nice. But we found that since neither grid ever get set to "display:none" (in order to achieve the animation effect, I'm sure), we had to set z-index of the "hidden" grid to -1 in order to add clarity about which grid was currently active (click events were somewhat unpredictable which grid we were clicking on). Eventually we also put a delayed display:none to avoid other issues.

Hmm. It sounds like we may want to improve CrossfadeStage (which is providing the crossfade effect) to address the issues you mention. Can you elaborate on what you mean by "provide clarity" and those "other issues"? That might help us pin down a good resolution. Using `z-index` to hide things feels somewhat fragile; I'm wondering if we should use `visibility: hidden`. Or we may want to wait until the effect has completed and then apply `display: none`.

> I guess it would be helpful if you could fire an event after the animation has run its course, if possible.

This is a good idea. We have a mixin called TransitionEffectMixin that fires events tracking the progress of a transition effect, but CrossfadeStage doesn't use that mixin. I think adding an event to CrossfadeStage would be useful, and have made a note to look into that.

One complication is that, in this particular case, CrossfadeStage is used inside of Tabs, which is part of a general-purpose component class called Explorer. By default, I don't think the Tabs/Explorer is not going let events raised by the internal CrossfadeStage bubble up to the outside where you could observe them. So we'd probably need to define a general convention by which property changes with async visual effects (in this case, changes in `selectedIndex`) communicate when the effects have finished, and then arrange to have such events get bubbled up from internal parts like CrossfadeStage to the outside page.

> I recognize this isn't part of your main component offering, but just wanted to let you know what our experience was.

The SereneTabs demo isn't an official part of Elix, but the CrossfadeStage it's built on is. So I'd like to see if we can find a way to address this.

**Comment by bahrus** [comment]
I created a [demo](https://bahrus.github.io/elix/tabTest3.html), which, if I'm not mistaken, may indicate something is amiss.

What you see when open the page appears to be Standard Rooms Detail, which is a details element, inside of which is a button.  Expanding the summary ought to show the button inside.  It doesn't (for me).  But when I switch to the Deluxe button, I see the Deluxe Rooms Detail expanded.

**Comment by JanMiksovsky** [comment]
Thanks for the demo. Today I Learned that setting `opacity: 0` [still leaves an element clickable](https://stackoverflow.com/questions/4675916/css3-element-with-opacity0-invisible-responds-to-mouse-events).

As suspected, it looks like we'll need to wait until the animation completes, then hide the item with `visibility: hidden` or `display: none`.

I need to give this problem more thought, and will report back when I've figured how we'll handle this.

**Comment by JanMiksovsky** [comment]
I've filed new issue #105 to track the opacity issue and the related request for an event that fires when the selection effect is complete.
