### ISSUE TITLE
Popups positioning in overflow hidden containers

### ISSUE THREAD

**Issue by MapTo0** [elix/elix#117]
Hello all,

First of all, great job!
While playing around with your components I noticed that popups are absolutely positioned which makes them be hidden when they are wrapped within an element that has `overflow: hidden` style. Is this already considered and a known limitation?

Example: https://codesandbox.io/s/patient-feather-892wf?file=/index.html

**Comment by JanMiksovsky** [comment]
Thank you for your kind words!

For now, the clipping is a known limitation.

Sadly, the web platform doesn't currently provide a reliable way for an element to definitively put itself on top of all other elements on the page. In addition to the overflow issue you raise, anything that introduces a [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) can also cause a popup to be clipped.

To my knowledge, there is no good general way around such problems — introducing a workaround for one situation may complicate using the same component in a different situation. We've tried to keep things as well-factored as possible so that people with specific needs might be able to build variations of our components that use different styling to achieve the effects they need.

As it turns out, I'm working with a group of people to try to pursue a standards-based solution to the problem with the W3C/WHATWG — but any such solution will likely take a long time to get approval and cross-browser adoption.

Sorry I don't have a better answer at this point.

**Comment by MapTo0** [comment]
Thanks for your answer!

> As it turns out, I'm working with a group of people to try to pursue a standards-based solution to the problem with the W3C/WHATWG — but any such solution will likely take a long time to get approval and cross-browser adoption.

Can I follow this discussion somewhere?

**Comment by JanMiksovsky** [comment]
Sorry for the slow response.

I'm hoping to submit some material for discussion at the W3C TPAC conference this coming October, and can let you know when there's something to look at.

For now, since I don't think we can do more to address the limitation you asked about, I'd like to close this bug. If either of us see an opportunity to improve Elix overlays/popups in the meantime, we can reopen.

**Comment by MapTo0** [comment]
Are there any updates on that topic?
