### ISSUE TITLE
standalone downloadable version?

### ISSUE THREAD

**Issue by c-cube** [elix/elix#118]
the components look really nice, but if one wants to try them in a mostly-server-side context (maybe with a sprinkle of js) using node seems very overkill. Is there a reason elix is not on cndjs or doesn't have a minified `.js.zip` download link?

**Comment by JanMiksovsky** [comment]
I'm not quite sure you mean when you say you want to use Elix web components on the server side. Can you elaborate?

By "using node", I assume you're talking about consuming the elix package via npm? For npm, we decided long ago that we wouldn't focus on providing pre-built distributions of Elix because: a) it was non-trivial work and, b) it wasn't clear how to do that in a way that would meet the needs of enough people.

Elix already includes a very large number of components, and most people only need a small handful of those. It makes sense to let people handle bundling themselves so that they're only including the components they actually need. For quick experiments, people also have the option to use an npm CDN like https://unpkg.com and import the source file directly.

**Comment by c-cube** [comment]
> I'm not quite sure you mean when you say you want to use Elix web components on the server side. Can you elaborate?

I mean, a basic website with server-side generated html, but using web components (custom elements) to get a richer set of widgets, including tabs, combo calendar, list with search, etc. I'm not a frontend programmer so I tend to avoid javascript!

> For quick experiments, people also have the option to use an npm CDN like https://unpkg.com and import the source file directly.

Ah, didn't know about that, thank you.
