### ISSUE TITLE
Elix elements aren't observed

### ISSUE THREAD

**Issue by hydroper** [elix/elix#126]
#### Issue

`elix-hamburger-menu-button` doesn't work, no menu icon and no overflow hidden. There's no console error too.

#### Reproducing

Create a Laravel project with `laravel new elix-proj` and edit `webpack.mix.js` with the line:

```js
mix.js('resources/js/elix.js', 'public/js')
```

Set the contents of the view `welcome.blade.php` to:

```html
<!doctype html>
<html>
<head>
    <script type="javascript" src="{{ mix('/js/elix.js') }}"></script>
</head>
<body>
    <elix-hamburger-menu-button style="float: right">
        <button>Store</button>
    </elix-hamburger-menu-button>
</body>
</html>
```

Create `resources/js/elix.js` with:

```js
import Input from "elix/define/Input";
import HamburgerMenuButton from "elix/define/HamburgerMenuButton";
import AutoSizeTextarea from "elix/define/AutoSizeTextarea";

new Input;
new HamburgerMenuButton;
new AutoSizeTextarea;
```

Run:

```bash
$ composer install
$ npm install
$ npm install elix --save-dev
$ npm run dev
$ php artisan serve
```

**Comment by JanMiksovsky** [comment]
Thanks for filing an issue.

We have no familiarity with this framework, and in our experience frameworks often introduce confounding factors that prove to be the source of bugs. Often issues that have been attributed to our components turn out to be issues in how a framework is trying to use web components; that is, the issue is with the framework (or the bundler, etc.) and not the component. But we also don't have the resources to install, configure, or learn the wide range of frameworks and other tools available to web developers to be able isolate such problems ourselves. It's hard enough to focus our efforts on getting our components to work in plain JavaScript and to comply with the platform standards.

So the most helpful would be for you to reproduce the problem in plain JavaScript. Without that, it's hard for us to provide guidance.

Beyond that, it might help if you could identify which Elix components _do_ work in your environment. For example, a HamburgerMenuButton includes plain Button and Drawer components — are you able to use those?

**Comment by hydroper** [comment]
@JanMiksovsky It looks like my script elix.js (which imports the components) doesn't execute. The Webpack generated script contains the Elix components and elix.js (which is like `import "elix/define/Button";`), but Webpack generates 2 entries for elix.js (the last one is empty):

```js
/***/ "./resources/js/elix.js":
/*!******************************!*\
  !*** ./resources/js/elix.js ***!
  \******************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

__webpack_require__(/*! elix/define/Button */ "./node_modules/elix/define/Button.js");

__webpack_require__(/*! elix/define/Drawer */ "./node_modules/elix/define/Drawer.js");

__webpack_require__(/*! elix/define/Input */ "./node_modules/elix/define/Input.js");

__webpack_require__(/*! elix/define/HamburgerMenuButton */ "./node_modules/elix/define/HamburgerMenuButton.js");

__webpack_require__(/*! elix/define/AutoSizeTextarea */ "./node_modules/elix/define/AutoSizeTextarea.js");

alert(1);

/***/ }),

/***/ 1:
/*!************************************!*\
  !*** multi ./resources/js/elix.js ***!
  \************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

module.exports = __webpack_require__(/*! C:\Users\PadrÃ£o\Documents\org.recoyx\recoyx-org-site\resources\js\elix.js */"./resources/js/elix.js");


/***/ })
```

`alert(1)` doesn't execute.

**Comment by hydroper** [comment]
The issue was just the attribute `type="javascript"`. I can't believe... Thanks for Elix!

**Comment by JanMiksovsky** [comment]
We're glad you were able to resolve your issue.
