### ISSUE TITLE
A11y Issue with navigating the DateComboBox component.

### ISSUE THREAD

**Issue by rdytogokev** [elix/elix#132]
Begin with a clear and concise description of the bug.

**Steps that reproduce the issue**
1. Go to your documentation page for the DateComboBox. [https://component.kitchen/elix/DateComboBox](https://component.kitchen/elix/DateComboBox)
2. Using the keyboard only (no mouse or trackpad) try to select a date from the calendar dropdown.

**Expected behavior**
I expected to press the "Enter" key and use the arrow keys to move around, the press "enter" again when the preferred date is reached. This is how the CalendarMonthNavigator component works. [https://component.kitchen/elix/CalendarMonthNavigator](https://component.kitchen/elix/CalendarMonthNavigator)

Thanks

**Comment by JanMiksovsky** [comment]
Thanks for submitting your report.

In a combo box component, the keyboard focus remains in the text box. In order to let the user navigate the cursor in the text box with the Left and Right arrow keys, DateComboBox doesn't handle those keys. (For consistency, it also does not handle Up or Down.) The CalendarMonthNavigator instance shown in the popup never gets the focus, so its arrow key handling can't come into play.

Instead, DateComboBox supports directional date navigation in the calendar with Ctrl+Shift+Left, Ctrl+Shift+Right, etc.

We've updated the [DateComboBox documentation](https://component.kitchen/elix/DateComboBox) to note that.
