### ISSUE TITLE
SlidingStage interferes with tab navigation

### ISSUE THREAD

**Issue by geonanorch** [elix/elix#133]
After going through all focusable elements of a `SlidingStage` item, tab navigation jumps to the next `SlidingStage` item (1st problem) and causes a partial scroll of that item in order to make the focused element visible (2nd problem).

**Steps that reproduce the issue**

My use case is a multi-page wizard implemented as a form containing a `SlidingPages`/`SlidingStage` and a pair of buttons for validation+navigation. Each page contains focusable elements such as INPUT:

```
          <elix-sliding-pages>
            <div>
              <h2>PAGE 1</h2>
              <input name="input1a">
              <input name="input1b">
            </div>
            <div>
              <h2>PAGE 2</h2>
              <input name="input2">
            </div>
          </elix-sliding-pages>

          <div>
            <button style="float: right">Next</button>
            <button>Previous</button>
          </div>
```

Click on `input1a` ("start"), then hit the 'tab' key a first time, focus goes to `input1b`. Hit the tab key again, focus goes to `input2`. The second item ("PAGE 2") becomes partially visible.

**Expected behavior**
Focusable elements, which are in items not currently shown, should not participate in tab navigation. Instead, navigation should leave the item and jump to the next focusable _outside of_ the `SlidingStage` component (here the "Next" button).

Methink the proper behavior would be attained if not-shown items had `visibility: hidden`. This does not seem to interfere with the transition effect, at least when tested by adding the rule: 
```
      elix-sliding-pages > [aria-selected="false"] {
        visibility: hidden;
      }
```

**Comment by JanMiksovsky** [comment]
This is a great issue! Many thanks for bringing this to our attention, and for the thought you put into the explanation and proposed solution.

In general, we haven't done much work on hosting focusable elements in components in the carousel family, so addressing this would usefully expand the envelope of what these components can do. Among other things, I believe the same issue will apply to components like Tabs, which are generally used to contain pages that contain focusable children like inputs.

That said, after some initial experimentation, I'm realizing that this may be extremely challenging to fix.

I've pushed a #sliding-stage-focus branch that contains some initial experimentation on fixing the problem in SlidingStage. SlidingStage is a more fundamental component, so probably a more universal place to provide a solution.

The biggest issue is that marking something as `visibility: hidden` also removes it from the accessibility tree, breaking accessibility for components like Carousel. While a carousel has the focus, we want a screen reader to be able to announce the user's current position in the set. Example: in the [carousel.html](https://component.kitchen/demos/carousel.html) demo, when the focus moves into the carousel, Apple Narrator should announce "Mountain Lake (1 of 5)".

However, if those other 4 items in that carousel are marked `visibility: hidden`, those items are removed from the accessibility tree. Accordingly, the screen reader will report that there is only 1 item in the carousel: "Mountain Lake (1 of 1)".

So that approach does not appear to be viable. Other approaches:

* I looked into whether the [proposed `inert` attribute](https://github.com/WICG/inert#tldr), which can mark a subtree as inert, might be useful here. However, not only is that proposal is still in the experimental stage, the proposal also says, "a node which is inert should also be hidden from assistive technology." So that's out.
* I tried setting `tabindex="-1"` on non-active items, but that's not sufficient to prevent their child elements from getting focus.
* We could try searching for focusable children inside non-active items and mark those with `tabindex="-1"`. I think that will run up against the fact that an item inside the SlidingStage might itself be a web component with focusable shadow elements. I suspect that marking such an item as not focusable will nevertheless leave the shadow elements focusable.
* A completely different method would be to try to listen for focus events bubbling up through non-active items. In such a case, the component could try to find the next focusable element after the SlidingStage and put the focus there. (Or, if the user is holding down Shift, try to find the previous focusable element before the SlidingStage.) That approach feels brittle, and again wouldn't handle the case where an element that is not itself focusable may have a shadow containing a focusable subelement.

Given this, at the moment I don't see a promising path forward. I'll keep thinking about this. In the meantime, if you have thoughts or other ideas, please let me know.

**Comment by geonanorch** [comment]
You are welcome, glad that we could contribute something back :-)

You guys are clearly more knowledgeable than we are regarding accessibility. As for me, upon reading your comment my first reaction was that maybe something is wrong or missing in the specs... I then had a look at W3C's [WAI-ARIA Authoring Practices 1.2](https://www.w3.org/TR/wai-aria-practices-1.2/#tabpanel) and guess what: they do not describe what happens when tab navigation moves on from the last focusable element of a tab panel. Do you feel like submitting this particular issue to them ? Or do you know another committee ?

This would be for long-term resolution of course. Regarding what you already tried, I think that I can confirm the limitation with shadow elements: our wizard actually uses `elix-input` and other web components instead of plain elements, and I just gave it a try, setting `tabindex="-1"` on the web component does not prevent focus in elements within. I also share your view that the last approach (trying to focus programmatically) will only be trouble.

By the way I do not get 100% the carousel+narrator example you mentioned: if a user enters a particular stage (or tabpanel, etc...) to activate an image, then in that new context there is no reason to consider other panels or their number? The Narrator might rather have announced beforehand (as the first stage/tabpanel got focus) _"Panel (1 of 5)"_ ?  Really no offense intended, as I said we are rather n00bs where accessibility is concerned.

At any rate this made me think of another alternative: assuming that an attribute/class would indicate for all stages/tabpanels if focus is somewhere within a stage/tabpanel, then we could restrict invisibility to that state. Initially everything would be visible, and only when entering a specific stage/tabpanel would other stages/tabpanels become invisible. Not elegant, but maybe a better compromise?

**Comment by JanMiksovsky** [comment]
> By the way I do not get 100% the carousel+narrator example you mentioned: if a user enters a particular stage (or tabpanel, etc...) to activate an image, then in that new context there is no reason to consider other panels or their number? The Narrator might rather have announced beforehand (as the first stage/tabpanel got focus) "Panel (1 of 5)" ? Really no offense intended, as I said we are rather n00bs where accessibility is concerned.

Apple Narrator, at least, announces the "Panel (1 of 5)" bit before announcing the text input that gets the focus. Given that, I think it'd be confusing if it announced "Panel (1 of 1)". And we definitely want that "1 of 5" announced for cases where a SlidingStage (Carousel, etc.) contained non-focusable elements like images. I also was hoping to avoid having to branching logic in SlidingStage (and so in Carousel, etc.) that tried to guess whether pages/panels inside contained focusable elements.

Your comments did lead me to think of another approach. Rather than applying `visibility: hidden` to the pages inside a SlidingStage, we could apply that styling to elements _inside_ those pages. So your sample above becomes:

```css
elix-sliding-pages > [aria-selected="false"] > * {
  visibility: hidden;
}
```

That leaves the inactive pages visible to the screen reader, but also hides the focusable elements inside those out-of-view pages (so the Tab key will skip them).

One minor wrinkle is that it's difficult to apply such styling inside a component like SlidingStage, as the `::slotted` selector can't be used as part of a more complex rule (here, targeting the children of the slotted elements).

One option would be to create a component that was used in place of the `div` for the pages inside the SlidingStage. I think that component could then have a `:host([aria-selected="false"]) ::slotted(*)` selector . You could create such a component yourself, or we could add such a component to Elix.

Aside: I'd like to have SlidingPages (and another related component called Modes) apply a `selected` attribute to the selected page. The list components already do that. This would let the styling use `:not([selected])` instead of `[aria-selected="false"]`, which I think more closely represents the developer's intent.

Also: I'd also like to address a separate bug I noticed in playing with your scenario: SlidingStage navigates when the Left and Right arrow keys are pressed, which prevents those keys from being used to navigate the cursor inside an input on a page inside SlidingStage.

In any event, please give that styling a try and confirm if that approach works for you.

**Comment by geonanorch** [comment]
Sure, `> [aria-selected="false"] > *` works for us.

I can see the problem with integrating such a rule inside `SlidingStage` / elix, as it implies some kind of influence on slot inner content, which seem to be a frontal attack against web components ;-)
Adding another component feels contrived, at least as an elix user I would not expect to have to do that. Maybe if it could be automated within `SlidingStage`... Do you see any impact in terms of styling (from an elix user perspective) `SlidingStage` and its siblings?
At any rate I still have the feeling that we are trying to solve a problem which originates in the ARIA spec and should ultimately be addressed there.

Indeed the left-right navigation is a problem ;-) Thank you, we had not noticed.

**Comment by JanMiksovsky** [comment]
Following up on my two comments above:

* I've updated SlidingPages and Modes to apply a `selected` attribute, so you can use `> [selected] > *` if you prefer. This change went out in the recent 14.1.1 release.
* I've updated KeyboardDirectionMixin to handle arrow direction keys as low-priority keys: they will only be handled if the component applying the mixin itself has the focus. With that, if you place an input inside a component like SlidingPages, if the focus is in the input, the arrow keys will navigate the insertion point cursor inside the input rather than navigating pages. That fix is up on master if you want to try it out, or you can wait for it to show up in the next Elix release (maybe later this month).

I've also made a note to bring your general question up the next time I connect with browser folks that work on accessibility.

With all that, I think we may have covered your original issue. If that's correct, shall we close this?

**Comment by geonanorch** [comment]
Impeccable follow-up :ok_hand:
* We indeed prefer `[selected]` (`* > :not([selected]) > *` based on the discussion above) and can confirm that 14.1.1 works for us.
* thank you for the arrow navigation fix, the fast turnaround is appreciated
* great if you can take up the matter with the right people, you can certainly make more impact that we can

Indeed the original issue is addressed, in fact with some side-benefit (arrow fix). This ticket was anyway more of a discussion on how to do it right and integrating the solution in elix.  If you would rather not use it to track the discussion with the browser / accessibility people, feel free to close (and thanks for asking in the first place).
