### ISSUE TITLE
Add ability to disable blur handling in popups

### ISSUE THREAD

**Issue by klobetime** [elix/elix#144]
We find ourselves commenting out the blur handler during development because it can wreak havoc with debugging:
https://github.com/elix/elix/blob/c768cb0e3be5ade1010baf9ecd2849d3ad0da093/src/base/PopupModalityMixin.js#L85-L86

It would be nice if there were a config option for this, or at least some way of temporarily removing this.

Thanks.

**Comment by JanMiksovsky** [comment]
Thanks for the suggestion.

When debugging popups, I've normally just selected the popup in the debug panel and invoked `$0.open()` to open it. Opening the popup that way prevents it from getting the focus, so it also won't close on blur.

That said, your suggestion is a good one. I've checked in a change so that `elixdebugpopup=true` on the URL will disable the close-on-blur behavior in both PopupModalityMixin (which tracks blur on the popup and document) and ComboBox (which tracks blur on the text input). With that, you can open a popup, and then switch to the debug panel to debug it.

If you'd like, please take that for a spin and let me know if that meets your needs.
