### ISSUE TITLE
Can Elix components be fully controlled by the developer?

### ISSUE THREAD

**Issue by mehdi-cit** [elix/elix#160]
I came from the very interesting video on https://youtu.be/mtHf7crZZIQ
One extreemly important note is that it mentioned that web components have to be as close to HTML as possible. However, in some of the code shown we have the web-component itself listening for events (so far so good) and then directly settings its state. Obviously, HTML elements do not set their state themselves but instead dispatch events about the user interaction/intent. It's the developer job to set the state and the HTML element would render itself accordingly.
I'm hoping this is the case with Elix component as well but I'm not sure from what I saw so far.
For instance, take a Tabs component with two tabs:
<Tabs>
<tab-1>First Text</tab-1>
<tab-2>Second Text</tab-2>
</Tabs>
Assuming the tab-1 is the active/selected one and the stage area showing text "**First Text**". If the user clicks on the tab-2 "header" that tab-2 becomes active/selected and the stage then show "**Second Text**".
If the above "web-component" behaved like native HTML elements, it'd have first dispatch an event, the developer would then decide if she wants the tab-2 to become active or not, or do whatever the developer wishes to do! 
I'm hoping Elix does use this principle!?

Such scenario is not that far fetched. Imagine, the tabs contained some text area that the user would fill and then save her filled-in text to some backend. A developer might want to halt the switching from tab-1 to tab-2 and present the user with a dialog with three options: 
1- discard changes and move to tab-2
2- save changes and move to tab-2
3- close this dialog and stay in tab-1 (the user wold manually continue her work on that text area).

I hope you guys got the point. I really love so many things about what I think Elix is and wish it does allow full control from the developer as described in the example above!

**Comment by JanMiksovsky** [comment]
Thanks for your message.

I think the native HTML elements actually do plenty of work without requiring (or permitting) the developer to be involved. When you type a character in an <input>, by default the character will be added to the input. When you select an option in a <select>, the option becomes selected. In either case, the develop does not need to do anything, and the element updates its own state. In many cases, the native element does raise a cancelable event. But I think it's incorrect to say that these elements are fully controlled by the developer.

With that in mind, most Elix components do provide default behavior. When you select an item in a DropdownList, that item becomes selected. When you swipe to open a DrawerWithGrip, the drawer becomes opened.

We're open to creating new events for specific use cases. Your tab scenario is an interesting one, and could be generalized to all components in the Explorer family. We've added that to our list of requests to address in future work on Explorer. If there are specific additional cases that should be covered with cancelable events, please let us know.

Since we've captured the suggestion, if there are no specific points remaining to address here, I'd like to close this issue.

**Comment by mehdi-cit** [comment]
Thank you for the prompt reply. I had the default HTML input element in mind while posting the above question/request. I just did not want to make the post too long. Obviously some HTML element do have a set of default behaviors (even though allowing full dev control -**always**- gives more flexibility). 
In my humble opinion, we should not try to list the scenarios where such canceling ability should be mixed-in. Rather, it should be (if possible) always possible (and by default) to give the developer full control. 
Maybe (_I am just thinking out loud here. Do not hold me to it_), by design, all internal state manipulation (exp setState) would only trigger/be-applied as a response to a "pre" event emitted by that component. So instead of a component having some `addEventListener('click' => setState({selected:true})) ` we'd have the component raising a notification such as `bus.notify({intent:"select-item", defaultMeth: () => setState({selected:true})})`
So -some how- if the developer doesn't specify a callback, the `setState({selected:true})` would be ran. Or maybe the dev might define her own callback and specify the component's default callback should still be ran. 

Please do not take this as criticism. I am a fan of your work and I couldn't stop thinking about Elix since I saw that video of yours! 

Humm, maybe one can implement state manipulation/flow-control as a mixin? With different implementations? .. Ok I should go to sleep now!

**Comment by mehdi-cit** [comment]
Please go ahead and close this issue if you judge if you feel that's the right thing to do here!

**Comment by mehdi-cit** [comment]
Let's see if one can "fully control" Elixs' components. But this time from a different angle!
I played a little with the react example to see if I can "bend Elix" to my will from the "outside". 
Wrapping a component and letting the wrapping code be responsible of the logic.
I took the example you have here of using **`elix-list-box`** from within React and see if I can make it behave in an expected way. The idea here is to see how flexible these Elix components can be (like the tabs example I gave earlier in this thread).
Usually, an elix-list-box would allow you to select an element and that's about it. What if I make it behave in a different way (does not matter if this particular example makes sense).
Please look at https://stackblitz.com/edit/react-pekdhz?file=src%2FApp.js
For such approach to work, we need two things. 
**1- First**, all Elix components must dispatch all kind of events that the developer would be interested in. The more events the developer can listen to the more junctions points she can intervene and drive the underlying web components. This would render the elix components more flexible!
**2- Second**, the developer must have ways to intervene on said events. Here, we need a way to "force" the Elix component to be in any state the developer wants/needs. This is done by simply setting the state of the Elix components. For this second point to hold true, the Elix component must allow us to alter their state from the outside (the more detailed the better. I.e. the more we can drill into the components state and set it the better).  

What do you think of this approach @JanMiksovsky ? Can it work? if yes, is it advisable (any reason one should not do such thing)?

PS: In the linked example https://stackblitz.com/edit/react-pekdhz?file=src%2FApp.js
Does the **`elix-list-box`** dispatch any event if the user clicks/select an already selected item? ("selected-index-changed" is not fired if the selected index has not changed!). Actually, I cannot see why such event would be useful. But isn't that the point of Elix ( and the above two points)? We need not try to foresee all possible use cases! Just enable **by design** the developer to intervene at any possible junction and apply desired changes on any of Elix's components!

**Comment by mehdi-cit** [comment]
Oh, my[ little example]("selected-index-changed") does not work hen using the keyboard. Somehow, using the mouse "selected-index-changed" is only fired once, but with the keyboard up/down keys it looks like it's firing twice!

**Comment by JanMiksovsky** [comment]
This is a complex topic, so I'd like to break this into smaller parts.

First, a minor note that the hyphenated events like `selected-index-changed` are deprecated, and have been superseded by events with names like `selectedindexchange` for consistency with browser event names. The API section of the [docs](https://component.kitchen/elix/SingleSelectAPIMixin) describe the latter, but I do notice that the textual description on that page uses the older, deprecated name. We'll update the docs. In the meantime, I just wanted to let you know about the event name change, as the old events will be removed at some point in the near future.

Second, I think the reason you're seeing the index change twice is because your own code is modifying the index: the first event is a response to the keyboard, the second event is a response to your own code. (The real question to me is why this doesn't create an infinite loop.)

To your larger question, the idea of changing a component's behavior based on intercepting events is not something we've invested much time in. In general, Elix prefers to avoid getting into a situation where a developer must remove or override built-in behavior — that's usually a signal to us that the developer is beginning at the wrong starting point. Instead, we generally prefer for developers to compose the behavior they want from mixins. If they don't want some behavior, they can leave it out.

In the example you cite of doing something unusual on selection, our normal approach to this would be to create a list component from the basic mixins. If they don't want the default tap/click behavior, they can leave out TapCursorMixin. If they want unusual keyboard behavior, they can leave out KeyboardDirectionMixin and provide their own keyboard behavior. In this way, we're only using the behavior we want; we're not trying to override base class behavior, which in our experience can become hard to maintain.

That said, I can see the value of letting HTML developers have more control over UI behavior without having to create new components themselves. That's an interesting direction we could go in, but it would significantly expand the amount of situations we need to deal with, so it's not something we would entertain lightly.

To make the case for this, we'd need to see some compelling examples of where someone would _not_ want to have the cilcked/tapped item become selected. The most compelling example presented here may be the one you suggest where a developer wants to enforce modality in a set of tabs, forcing the user to do something before allowing them to switch tabs. I generally think that modality is something to be avoided, particularly in web designs. If modality is strictly necessary, other alternatives could be explored: e.g., one could disable the other tabs if for some reason they're not available, and reenable them when the user is allowed to switch tabs.
