### ISSUE TITLE
Location is not defined

### ISSUE THREAD

**Issue by geoidesic** [elix/elix#187]
**Steps that reproduce the issue**
1. Create a new Sveltekit app ` npm init svelte@next svelte-elix; cd svelte-elix; npm i elix; npm i; npm run dev;` – choose TypeScript from options.
2. Edit the about page to add a button `/src/routes/about.svelte`: add `import Button from "elix/define/Button";` within the `<script>` tags then add `<Button>click me</Button>` in the `<div class="content">` element.
3. Note the Vite errors: 
```
ReferenceError: location is not defined
    at /node_modules/elix/src/base/internal.js:597:39
    at instantiateModule (/Users/repo/svelte-elix/node_modules/vite/dist/node/chunks/dep-e9a16784.js:68197:166)
7:57:20 PM [vite] Error when evaluating SSR module /node_modules/elix/src/core/ReactiveElement.js:
ReferenceError: HTMLElement is not defined
    at /node_modules/elix/src/core/ReactiveElement.js:27:37
    at instantiateModule (/Users/repo/svelte-elix/node_modules/vite/dist/node/chunks/dep-e9a16784.js:68197:166)
location is not defined
```

**Expected behavior**
Shouldn't get errors.

**Comment by JanMiksovsky** [comment]
I just noticed that this issue was filed back in May — many apologies for overlooking this. 🙇

The two ReferenceErrors above look like fundamental DOM classes aren't defined, which is unusual.

Can you reproduce the errors without using Svelte or other libraries/frameworks? We don't use Svelte or Vite, and generally need to focus our limited bandwidth on ensuring Elix works in a plain browser environment.

**Comment by JanMiksovsky** [comment]
Closing for now — if you can reproduce these errors in isolation (without Svelte/Vite), please reopen!
