### ISSUE TITLE
Filtered ListComboBox loses attachement to text input

### ISSUE THREAD

**Issue by naasking** [elix/elix#215]
I'm on Chrome 95.0.4638.69, Windows 10.

**Steps that reproduce the issue**
1. Go to Elix page for LisComboBox: https://component.kitchen/elix/ListComboBox
2. Ensure you are scrolled to the top so there is little room underneath the drop down so it renders above the text input.
3. Start typing so the list gets filtered, and you'll see it loses the attachment with the text box and it's just floating near the top of the screen: https://imgur.com/6q3ZOul

**Expected behavior**
The list is associated to the text input, so it should stay attached.

**Comment by JanMiksovsky** [comment]
This is an interesting bug!

Thanks for reporting it, I'll investigate.

**Comment by JanMiksovsky** [comment]
I've checked in a fix for this, which you can preview at https://test.component.kitchen/elix/ListComboBox.

Please confirm that this fixes the problem for you. This fix will go out in the next minor Elix release, probably later this month.

**Comment by marcricharme** [comment]
Fixes the position issue, but seems to have lost ability to scroll the list (scrollbars gone, mousewheel just closes the control).

**Comment by JanMiksovsky** [comment]
Apologies for the delay, I keep trying to find time to work on this. For now I at least want to reopen it so it's not forgotten.

**Comment by JanMiksovsky** [comment]
Thanks for your patience. I've once again deployed a fix to the test site at test.component.kitchen. As far as I can tell, this maintains the fix for the original FilterComboBox issue, while restoring the ability to scroll the list with the mouse wheel, etc.

There are still situations in which using the wheel to scroll the page will implicitly close the popup if the mouse isn't over the popup list. That's generally expected. I've tried comparing the ListComboBox and FilterComboBox pages on both the main component.kitchen site (with the old components and buggy FilterComboBox) and test.component.kitchen (with the new components). From what I can see, the situations in which the mouse wheel closes the popup are the same — that is, no new regressions have been introduced.

@marcricharme As your time allows, please let me know if this looks good to you.
