### ISSUE TITLE
[Question] Why Gulp over WebPack?

### ISSUE THREAD

**Issue by Nevraeka** [elix/elix#22]
Why use Gulp to run Webpack? Is it a usability or a complexity issue? I am just curious.

**Comment by JanMiksovsky** [comment]
Using Gulp was a way of centralizing the entry point for all the project's tasks/tools, and also let us invoke webpack as part of a larger `build` task that also generated documentation.

As it turns out, though, we're currently doing some substantial rework on our tool chain, and have been revisiting our decision to use Gulp. We may be able to drop the use of a few of our custom tasks, and then the only task we might have left would be webpack, at which point we just invoke that without Gulp.

**Comment by Nevraeka** [comment]
@JanMiksovsky in the new builds, how big do the webpack bundles get? Does the new system remove all unused modules? Sorry for the 20 questions on this :(

**Comment by robbear** [comment]
Elix's build process is mostly irrelevant to clients of Elix. The idea is to provide ES6 code via imports to clients, and clients manage their own application build process including selecting which elements/mixins they want from the full source tree that they get when using npm/yarn to install the Elix package.

Whatever build process is contained within Elix is meant for convenience only - the building of ES5 bundles including one for all Elix code, one for unit tests, and one for demos that is incidentally consumed by the elix.org web site. What I mean by convenience is that upon the installation of the package, a developer can immediately script-include the full build/elix.js output to begin development without first having to focus on their own build process.
