### ISSUE TITLE
[Design] What other basic elements can contributors work on?

### ISSUE THREAD

**Issue by Nevraeka** [elix/elix#25]
This is a issue to discuss what elements and/or collections should be created for Elix. What are the ways to determine if a element is right for this repository? Solely the gold standard or other criteria?

#### Here are a few ideas to start...

🔘 Tabs Family 
⚪️ Inputs?
⚪️ Buttons?
⚪️ Spinners?
⚪️ Layout and media query families?

**Comment by robbear** [comment]
FYI - The core team will be discussing next steps regarding the implementation of an overlay element vs focusing first on carousel at its 24 April meeting. We'll be talking about a road map for prioritizing work on an ongoing basis. Suggestions for new work are encouraged and welcome through Elix's RFC process, so as interest in Elix grows, we'll get a sense for priorities as contributors chime in.

A guiding line, though, is what elements are most useful to the widest range of developers possible, including support for the most common UI patterns, and where deep quality supporting a wide range of applications is most important. So the Gold Standard fits in here as a criteria, but mostly in the sense that all Elix elements are meant, by definition, to support it.

Another consideration as contributors come up to speed on the code base is what mixins already exist that make it easy to introduce a new element. And, of course, contributors should consider the design and implementation of new mixins that create a snowball effect of new elements that take advantage of the growing pool of mixins.

This issue is a good place for discussion outside the core team meetings to solicit feedback on an informal basis before investing in writing up an RFC.

**Comment by Nevraeka** [comment]
Thanks for the reply @robbear . That's awesome about the discussions going on with the core team. An overlay sounds much more lower level from an UX & RWD standpoint. Carousels would likely have more sub-elements in it's composition. I think Brian Kardell & a few others would have great ideas on potential elements to add to Elix.   

cc @bkardell @RevillWeb @jouni @jshcrowthe @chiefcll @onishiweb @granze @Link2Twenty @prateekjadhwani @filaraujo @webreflection

**Comment by jouni** [comment]
Thanks for the heads up @Nevraeka!

I’ve also thought about an overlay, which would indeed be a building block needed by many other higher level components. I just tend to fall into the trap of over-designing this kind of a thing, and the technical complexity grows pretty fast when you start taking too many variables into account. But I think it would at least be a good exercise to try and design a general purpose overlay element and scope out a minimal starting point for it.

**Comment by ThomasDeutsch** [comment]
I am glad i found this project.
I work with Input Forms a lot and i have some major issues with some of the inputs provided by the browsers.

1. Date Input ( not date-pickers)
For many Dates Inputs, you do not want a datepicker to pop up.  For example, i do not want to scroll through years and years to get to my birthday. I know my birthday and i simply want it to write it into an input.  For this to happen, i think an input-mask-mixin is a good solution - and it can be reused for many other inputs as well.

2. Formatting Inputs ( show format during input )
In some cases, i would like to format a user input right in the input box, right after the first character is put into the input box.
For example, i want a user to enter an amout of money into the box, He enters 1 and the input box could show 1.00 ( maybe with .00 in a slightly lighter color)

2. Autocomplete.
I know an excellent autocomplete input.  It is the chrome search bar right under the tabs in your chrome browser. If i enter a search-term, the first pick is always highlighted and i can simply press enter, or up and down to select different items.


I would like to give you some feedback - something that came to mind when i first discovered your page ( i hope you do not mind )
Before i would write an RFC, i would love to share some thoughts. Maybe a codepen with some solution i came up with - i can not find any information that incourages this.  I feel the need for a discussion before i think that my solution is solid and well thought.
Yes, i can create a comment as @robbear mentioned - but in my opinion this is a very important part of the whole process.   
When i enter the page, i can see some compoenents and documentation, but no place where i can start writing a component to share and to start the discussion.

On the frontpage, the left menu is a bit broken. It jitters, when the mouse cursor is on the right side of it. (you need to be careful with this, when you are talking about the golden standard on the same page) And the background image is a bit confusing ( maybe it would be a good idea to remove it ).

**Comment by JanMiksovsky** [comment]
@ThomasDeutsch Many thanks for saying hello.

All three of the components you mention are interesting.

We're always interested in suggestions or thoughts in any form. It's not necessary to start things with an RFC. You're also welcome to send me thoughts in email at jan@component.kitchen, or to tweet links to @ElixElements with a codepen/jsbin sample.

The UI issue you mention on elix.org is a known bug. We've wanted to fix it for a while, but are just beginning a redesign of the site, and decided we'll fix the problem when we implement the new design. (Depending on how the design turns out, we may end up with a different navigation UI, and so we didn't want to spend time fixing a problem with the current UI.)

**Comment by robbear** [comment]
Closing this issue. Ideas, suggestions will come through direct email, Twitter, or other communications until we set up a generalized form for idea submissions.
