### ISSUE TITLE
Carousel draggable with mouse

### ISSUE THREAD

**Issue by Nudelsieb** [elix/elix#84]
This is related to the examle https://component.kitchen/elix/Carousel

From other carousels/sliders I am used to be able to move the slide by dragging it with the mouse button down. Currently, it seems that the default event is to drag/drop the image inside the slide. It's probably just a missing preventDefault to fix that issue. Or is this behaviour by design?

**Comment by JanMiksovsky** [comment]
For the time being, we've built our stock Carousel component so that mouse drags do not swipe the carousel. This is by design. Like all our components, we'd like Carousel to be fairly conservative in its assumptions. Some people will want mouse-drags, others won't.

In the case of a drag on an image, the default browser behavior is generally to let the user drag-and-drop the image to the desktop or another app. We'd like to leave such behavior in place. Moreover, Carousel is designed to host any kind of content, not just images. Some apps use carousels for tutorials, for example. Automatically supplying mouse-drag support might interfere with such scenarios.

(That said, in investigating this issue, I've noticed that changes in the recent Elix 4.0 release related to keyboard focus handling appear to have broken the ability to drag-and-drop images out of a carousel. I'm going to investigate to see what will be required to restore that feature.)

We generally avoid defining component properties to turn behaviors (like mouse-drag support) on and off. Instead, we'd rather define base components classes with small feature sets, then extend those base classes with mixins and subclasses that add additional behavior.

In this case, it should be possible to create a mixin that adds the mouse-drag feature. We'd like to get to that mixin at some point, but it may take some time before we can do so. In the interim, if you're interested in creating such a thing yourself, we can try to offer guidance on how to do so.

**Comment by Nudelsieb** [comment]
I will see what I can do when I get to it. Closing this for now.

**Comment by JanMiksovsky** [comment]
Okay. We've been actively working on restoring the broken drag-and-drop of images, and that should be in our next release.

If you'd like to try working on this at some point, let me know and I can provide some suggestions for how to go about it.

**Comment by JanMiksovsky** [comment]
Just to follow up on this: the latest Elix release has now restored support for default drag mouse behaviors like drag-and-drop of images out of components like Carousel.
