### ISSUE TITLE
Feature Request : package it as monorepo

### ISSUE THREAD

**Issue by mrin9** [elix/elix#85]
I have a use case where I would like to use/extend a single component from elix. 
importing the whole package makes my extended component too bulky.
Would you consider restructuring this project as a Monorepo and logically separate the shared and unique code into individual sub-packages ?

**Comment by Nudelsieb** [comment]
On that note is it possible to es6 import separate components in a js module, e.g. in a Ract, Vue or Angula component?

**Comment by mrin9** [comment]
hmm, given the situation I agree with you. 
The other option that I can think of is to use a bundler like webpack and generate a single chunk for each component. Webpack should take care of importing all its dependencies and generate a standalone output of each component say in `dist` folder  and then people like me can just use a 
```
<script src="https://unpkg.com/elix@(version)/dist/component.js"></script>
```
although I dont know, can we cleanly create such bundles with webpack.
But if it is too much of a hassle, let things be as is we can revisit this later

**Comment by Nudelsieb** [comment]
You could make the mixins and the components npm packages and the rest is just used as is. Some redundancy is not bet if it leads to and easier to use and/or more efficient product.

WRT to a core module: I just had a quick look and most of your components make regular use of 
`updates.js`, `symbols.js` and `template.js`.  Maybe it's woth combining this.

WRT to my question above is that I did not really know how to add components to a project. I want to avoid script tag. So and ES6 import in a module that wants to use a component should be good. But as it stands now that's not possible, given the reasons above. So do I just import the whole project as ES6 module?

**Comment by Nudelsieb** [comment]
Another note. My use case is that I would like to use your Carousel in my own web component (created with StencilJS), but I do not want to include the whole library just for one component.

**Comment by JanMiksovsky** [comment]
@mrin9 A significant problem with distributing bundled output like that, and a general problem with creating packages for each component, is that each bundle ends up with its own copy of the shared Elix files.

* Two components that look very different, such as Carousel and Tabs, actually share something like 90% of their code. So someone who imports both packages ends up with substantial duplication.
* Our components currently auto-register themselves with the browser. Since two distinct components may easily share subelements, each packaged component will try to register the subelement. E.g., both Carousel and Tabs will try to register an element with the name `elix-explorer`. The second such registration attempt will fail and throw an exception. We'd like to eventually offer ways of importing components with auto-registration, but that's a separate piece of work.

For now I'd like to close this issue, then revisit periodically to see if it would be appropriate to tackle this. I'm hoping we can eventually work towards making it very easy to use a single Elix component in a project.

**Comment by JanMiksovsky** [comment]
@Nudelsieb If the Quick Start section I added for #86 doesn't help, please file a separate issue. Thanks.

**Comment by JanMiksovsky** [comment]
Just following up on this now that Elix 4.0.0 has been released with a much smaller package footprint.

Package size is now 150K over the wire, 587K uncompressed. The previous on-disk size, not counting devDependencies, was more than 20MB.

@mrin9 Many thanks for your suggestion, which prodded us to take care of this!
