### ISSUE TITLE
AutoCompleteInput: missing event "selected-index-changed"

### ISSUE THREAD

**Issue by Nudelsieb** [elix/elix#87]
This is crucial to be able to set state depending on the selection. Of course you could manually poll the value but you actually want to be notified when the user change the value.

**Comment by Nudelsieb** [comment]
It is alos not documented how to use events the components to implement.

**Comment by JanMiksovsky** [comment]
AutoCompleteInput doesn't have a `selectedIndex` property, so it doesn't raise a `selected-index-changed` event. AutoCompleteComboBox is a more list-focused component, so it does have both that property and the corresponding event. But AutoCompleteInput is mostly just an input element, so doesn't provide either of those.

Like a standard `input` element, AutoCompleteInput should expose `change` and `input` events when the user types. These behave the same as the standard `input` element events.

To date, we haven't invested much time documenting events, because they're just regular DOM events, and can be wired up using whatever system you currently use. If you're using the DOM API directly, then you would use addEventListener.

We've been unsure how to document events like `change` and `input`, since they're essentially standard events. If we documented all the standard events, the documentation might become unwieldy. But, as you've found, if we don't document any of the events, it's unclear what events are available.

**Comment by JanMiksovsky** [comment]
The docs for input and textarea components — `Input`, `AutoCompleteInput`, `DateInput`, and `AutoSizeTextarea` — have been updated to include documentation of the `input` event. As the documentation notes, the `input` event is standard, and the components don't do any special work to raise that event, but given this issue, it seemed useful to surface support for the event in the documentation.

This change is now live on the Elix documentation site, so I'd like to go ahead and close this.
