### ISSUE TITLE
IE/Edge support?

### ISSUE THREAD

**Issue by AllNamesRTaken** [elix/elix#98]
I see that there is no IE11 and not even Edge support. But what is the limiting factor?
Can it run with a Webcomponents loader?
Does it need shims etc?
Is it compiling to ES6?

Would be helpful since I still need IE11 support in my project and found your efforts spot on. I would gladly contribute if this solved my problems.

**Comment by JanMiksovsky** [comment]
Thanks for your questions!

Elix supported IE 11 for a number of years via the web components polyfills. That proved to be an exercise in frustration. Elix components exercise the full range of the functionality implied by the web component API, and often revealed bugs in the polyfills that were challenging and extremely time-consuming to work around. At the same time, Elix did not see significant expressions of interest from companies that cared about IE.

When Microsoft announced its plans to release a Chromium-based Edge in December 2018, along with a plan to provide that version of Edge to customers that had previously been restricted to running IE 11, we made the decision to drop both IE 11 and Edge. We wanted to focus our time on the mainstream browsers, all of which generally work consistently and according to expectations.

The primary sponsor of Elix, Component Kitchen, is open to supporting IE 11 and the EdgeHTML-based version of Edge as work for hire under a support contract.

If a person or organization were willing to contribute their own time to invest in IE 11 and EdgeHTML support, the project would be open to discussing that. But that would be a significant undertaking. Even if the bulk of the work were performed by some other contributor, the project leads would likely have to invest a fair amount of their own time supporting that work, so we'd need to really understand the motivation involved and the resources that would be brought to bear in order to estimate the likelihood that it would pay off for the project overall.
