### ISSUE TITLE
Guide on How to ReactiveElement, ReactiveMixin

### ISSUE THREAD

**Issue by threeid** [elix/elix#99]
Hi JanMiksovsky and robbear,

I found that Elix Web Components are impressive. 
But missing guides and tutorials prevent me from using it.

Do you guys have any plan to write more guides and tutorials?
I want to learn how to use Elix's ReactiveElement with lit-html, [htm](https://github.com/developit/htm) and mobx.

I also would love to see ReactiveElement on this benchmark: https://github.com/vogloblinsky/web-components-benchmark.

Thank you 3000.

**Comment by JanMiksovsky** [comment]
Hi — sorry for not replying to your issue! You closed it before I could respond.

We're interested in expanding our documentation to help people get started with Elix more easily. We recently posted quick start projects for using Elix in [plain JavaScript](https://github.com/elix/plain-example) and [React](https://github.com/elix/elix-react), for example. We would love to do more, although our time is always constrained.

We don't view Elix as a competitor to frameworks like lit-html, mostly because there are so many teams working in that space. We prefer to focus our energy on creating great components that are directly usable by a broad audience using any framework. To do that, we've had to create our own core ReactiveElement, but we don't spent too much time trying to convince other people to use that as the basis for their own components.
